spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-2.coocppqxryzy.ap-northeast-2.rds.amazonaws.com:3306/database-2?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: ${{ secrets.JWT_SECRET_KEY }}  # 데이터베이스 암호로 변경해야 합니다
  jpa:
    hibernate:
      ddl-auto: validate

cloud:
  aws:
    region: # 환경 변수 github secrets에 등록 후 변경해야 함
      static: ${DREAMCONSUMER_AWS_REGION}
    s3:
      bucket: ${DREAMCONSUMER_AWS_S3_BUCKET_NAME}
    credentials:
      access-key: ${DREAMCONSUMER_AWS_S3_ACCESS_KEY}
      secret-key: ${DREAMCONSUMER_AWS_S3_SECRET_KEY}
    stack:
      auto: false # cloudFormation 기능 비활성화